# -*- coding: utf-8 -*-
"""파이썬 워크북 7장 문제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10T6kcQxsA1jUfGvbCYwb7zUBuqADtE5b

파이썬 워크북 7장 문제
"""

# 문제 1

a=10
b=20
def fswap(c, d):
    temp=c
    c=d
    d=temp
    return c, d

c=a
d=b
print("a 값은 ", a, "b 값은 ", b)
a, b=fswap(a, b)
print("a 값은 ", a, "b 값은 ", b)

# 문제 2-1

# a를 전역 변수로 사용하도록 변경
# global로 해결하기
b = 0
print("b의 값은", b)
b = 1
print("b의 값은", b)

def scope_test():
    global a
    a = a + 3
    print("scope_test() 함수 안의 a 값은", a)

a = 0
print("scope_test() 함수 밖의 a 값은", a)
scope_test()
print("scope_test() 함수 호출 후 a 값은", a)

# 문제 2-2

# a를 지역 변수로 사용하는 방법
# 지역 변수로 사용하기
b = 0
print("b의 값은", b)
b = 1
print("b의 값은", b)

def scope_test():
    a=0
    a = a + 3
    print("scope_test() 함수 안의 a 값은", a)

a = 0
print("scope_test() 함수 밖의 a 값은", a)
scope_test()
print("scope_test() 함수 호출 후 a 값은", a)

# 문제 3 - 코드 (1)

result=10
def fadd(num):
    b=result+num
    print("변수 result 값은", result)
    print("변수 b 값은", b)
fadd(10)

# 문제 3 - 코드 (2)

result=10 # ------------------> ①
def fadd(num):
    result=result+num # ------> ②
    print("변수 result 값은", result)

fadd(10)

# 문제 3 - 코드 3

result=10 # ------------------> ③
def fadd(num):
    global result # -----------> ①
    result=result+num # -------> ②
    print("변수 result 값은", result)

fadd(10)

# 문제 4

sua=10
sub=5
suc=7
max = sua
if sub > max:
    max = sub
if suc > max:
    max = suc
print("최댓값은", max)

# 문제 5

def fmax(sua, sub,suc):
    max = sua
    if sub > max:
      max = sub
    if suc > max:
      max = suc
    return max

sua=10
sub=5
suc=7
max = fmax(sua, sub, suc)

print("최댓값은", max)