# -*- coding: utf-8 -*-
"""파이썬 워크북 9장 문제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_dQlJL877tZQa466_NMeAccs68OSkbGj

파이썬 워크북 9장 문제
"""

# 문제 1

class Cadd:
    def fadd(self, a, b):
        self.x=a
        self.y=b
        self.hap=self.x+self.y

obj=Cadd()
obj.fadd(10, 20)
print("객체 obj 내의 인스턴스 변수 x의 값은", obj.x)
print("객체 obj 내의 인스턴스 변수 y의 값은", obj.y)
print("객체 obj 내의 인스턴스 변수 hap의 값은", obj.hap)

# 문제 2

class Cadd:
    def fadd(self, a,b):
        x=a
        y=b
        hap=x+y
        return hap

obj=Cadd()
ohap=obj.fadd(10, 20)

print("ohap의 값은", ohap)

# 문제 3

def fadd(a=1,b=2):
    x=a
    y=b
    hap=x+y
    return hap

ohap=fadd(10, 20)
print("ohap의 값은", ohap)
ohap2=fadd(10)
print("ohap2의 값은", ohap2)
ohap3=fadd()
print("ohap2의 값은", ohap3)

# 문제 4

class Cadd:
    def fadd(self, a=1, b=2):
        self.x=a
        self.y=b
        self.hap=self.x+self.y

obj=Cadd()
obj.fadd(10, 20)
print("객체 obj 내의 인스턴스 변수 hap의 값은", obj.hap)
obj.fadd(10)
print("객체 obj 내의 인스턴스 변수 hap의 값은", obj.hap)
obj.fadd()
print("객체 obj 내의 인스턴스 변수 hap의 값은", obj.hap)

# 문제 5

class Cadd:
    def fadd(self, a=1, b=2):
        self.x=a
        self.y=b
        self.hap=self.x+self.y
        return self.hap
obj=Cadd()
ohap1=obj.fadd(10, 20)
print("ohp1 값은", ohap1)
ohap2=obj.fadd(10)
print("ohp1 값은", ohap2)
ohap3=obj.fadd()
print("ohp1 값은", ohap3)

# 문제 6

class Cadd:
    def __init__(self, a=1, b=2):
        self.x=a
        self.y=b
        self.hap=self.x+self.y
obj=Cadd(10,20)
print("obj 객체 내의 인스턴스 hap의 값은", obj.hap)

# 문제 7

class Cadd:
    def __init__(self, a=1, b=2):
        self.x=a
        self.y=b
    def fadd(self):
        self.hap=self.x+self.y
        return self.hap


obj=Cadd(10,20)
ohap=obj.fadd()
print("ohap의 값은", ohap)

# 문제 8

class Cadd:
    def __init__(self, a=1, b=2):
        self.x=a
        self.y=b
    def fadd(self):
        self.hap=self.x+self.y
        return self.hap
    def fdiv(self):
        self.mok=self.x/self.y
        return self.mok


obj=Cadd(10,20)
ohap=obj.fadd()
omok=obj.fdiv()
print("ohap의 값은", ohap)
print("omok의 값은", omok)