# -*- coding: utf-8 -*-
"""파이썬 워크북 10장 문제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D1yrDbV2oSdSvVdCI6-arMSjVMwts3DO

파이썬 워크북 10장 문제
"""

# 문제 1-1

# turtleex1.py
import turtle
for x in range(1, 100, 1):
    turtle.forward(x)
    turtle.left(90)

# 문제 1-2

# turtleex3.py
import turtle
p=turtle.Pen()

for x in range(1, 100, 1):
    p.forward(x)
    p.left(90)

# 문제 1-3

# turtleex2.py

from turtle import *
for x in range(1, 100, 1):
    forward(x)
    left(90)

# 문제 2

class Cadd:
    def __init__(self, a=1, b=2):
        self.x=a
        self.y=b

    def fadd(self):
        self.hap=self.x+self.y
        return self.hap

    def fdiv(self):
        self.mok=self.x/self.y
        return self.mok

obj=Cadd(10,20)
ohap=obj.fadd()
omok=obj.fdiv()
print("ohap의 값은", ohap)
print("omok의 값은", omok)

# 문제 3

import week2

obj=week2.Cadd(10,20)
ohap=obj.fadd()
omok=obj.fdiv()
print("ohap의 값은", ohap)
print("omok의 값은", omok)

# 문제 4

class Cadd:
    def __init__(self, a=1, b=2):
        self.x=a
        self.y=b

    def fadd(self):
        self.hap=self.x+self.y
        return self.hap

    def fdiv(self):
        self.mok=self.x/self.y
        return self.mok

if __name__=="__main__":
    obj=Cadd(10,20)
    ohap=obj.fadd()
    omok=obj.fdiv()
    print("ohap의 값은", ohap)
    print("omok의 값은", omok)

# 문제 5

from week2 import * //from week2 import Cadd
obj=Cadd(10,20)
ohap=obj.fadd()
omok=obj.fdiv()
print("ohap의 값은", ohap)
print("omok의 값은", omok)

# 문제 6

class Ccarmake:
    carcount = 0 # 총 생산 자동차 대수를 저장하는 클래스 변수
    def ccolor(cls):
        colors = ["Red", "Blue", "Green", "Yellow"] # 다양한 색상의 자동차를 만들기 위한 리스트
        car_color = colors[cls.carcount % len(colors)] # carcount를 인덱스로 활용색상 결정
        cls.carcount += 1 # 자동차 생성 시 carcount 증가
        return car_color

# 색상이 결정된 자동차 생성
car1 = Ccarmake()
car2 = Ccarmake()
car3 = Ccarmake()
car4 = Ccarmake()

# 총 생산 자동차 대수 출력
print("총 생산 자동차 대수:", Ccarmake.carcount)