# -*- coding: utf-8 -*-
"""파이썬 워크북 3장 문제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14wZtJLVRdZpGc6TJn03Kl-BTbEf5CWna

파이썬 워크북 3장 문제
"""

# 문제 1

na = 21
if na % 2 == 0:
    sa="홀수"
else:
    sa="짝수"
print(na, sa)
print("if 문 종료됨")

# 문제 2

na = int(input("정수를 입력하세요."))
if na % 2 == 0:
    sa="홀수"
else:
    sa="짝수"
print(na, sa)
print("if 문 종료됨")

# 문제 3

age=int(input("나이를 입력하세요."))
if age >= 19:
    print("당신의 나이는 ", age, "살입니다.")
    print("입장하세요")
else:
    print("당신의 나이는 ", age, "살입니다.")
    print("보호자와 함께 입장하세요.")

# 문제 4

rmoney=int(input("이번달 용돈은 얼마인가요?"))
pmoney=int(input("이번달 지출 총액은 얼마인가요?"))
if rmoney > pmoney:
    print("용돈이 남았군요, 좀 더 쓰셔도 됩니다.")
elif rmoney == pmoney:
    print("용돈 관리를 잘했군요.")
else:
    print("용돈을 아껴 쓰세요.")

# 문제 5

MyName =''
if MyName =='hongkildong':
    print("확인되었습니다.")
else:
    print("틀렸습니다. 다시 입력하세요.")
    MyName = input()
    if MyName =='hongkildong':
          print("확인되었습니다.")