# -*- coding: utf-8 -*-
"""파이썬 워크북 4장 문제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1auFVZTpuRJ_Y-E6j_IL-S5mN8w778Kj6

파이썬 워크북 4장 문제
"""

# 문제 1 

for sb in range(0, 101, 1):
    if sb % 3 == 0:
        print(sb, end=" ")

# 문제 2

for sb in range(1, 11, 1):
    if sb % 3 == 0:
        continue
    print(sb, end=" " )

# 문제 3

sb = int(input("총합을 구하려는 수를 입력하세요."))
total = 0
for sb in range(1, sb+1, 1):
    total = total + sb
print("1부터", sb,"까지의 총합은", total, "이다.")

# 문제 4-1

for sb in range(1, 11, 1):
    total = 0
    total = total + sb
print(total)

# 문제 4-2

total = 0
for sb in range(1, 11, 1):
    total = total + sb
    print(total, end=" ")
print("끝")

# 문제 4-3

total = 0
for sb in range(1,11,1):
    total = total + sb
print(total)

# 문제 4-4

total = 0
for sb in range(1,11,1):
    total = total + 1
print(total)

# 문제 4-5

for sb in range(1,11,1):
    total = 0
    total = total + 1
print(total)

# 문제 5

sb=int(input("총합을 구하려는 수를 입력하세요."))
total = 0
sb = 0
while sb < 11:
    total = total + sb
    sb = sb + 1
print("1부터", sb-1,"까지의 총합은", total, "이다.")

# 문제 6

sa = int(input("총합을 구하고 싶은 정수 입력"))
total = 0
sb = 0

while True:
    total = total + sb
    if sa == sb:
        break
    else:
        sb = sb + 1
print("1부터", sa, "까지의 총합은", total, "이다.")

# 문제 7 - for 문

na = int(input("첫 번째 정수를 입력하세요."))
nb = int(input("두 번째 정수를 입력하세요."))
total = 0
for sb in range(na, nb+1, 1):
    total=total + sb
print(na,"부터",nb,"까지의 총합은", total,"이다.")

# 문제 7 - while 문

na = int(input("첫번째 정수를 입력하세요."))
nb = int(input("두번째 정수를 입력하세요."))
total = 0
sb=na
while sb < nb+1:
    total=total + sb
    sb=sb+1
print(na,"부터",nb,"까지의 총합은", total,"이다.")

# 문제 8 - for 문

na = int(input("첫 번째 정수를 입력하세요."))
nb = int(input("두 번째 정수를 입력하세요."))
total = 0
for sb in range(na, nb+1, 1):
    if sb % 3 == 0:
        total=total + sb
print(na,"부터",nb,"까지의 3의 배수의 총합은", total,"이다.")

# 문제 8 - while 문

na = int(input("첫 번째 정수를 입력하세요."))
nb = int(input("두 번째 정수를 입력하세요."))
total = 0
sb=na
while na < nb+1:
    if na % 3 == 0:
        total=total + na
    na=na+1
print(sb,"부터",nb,"까지의 3의 배수의 총합은", total,"이다.")

# 문제 9

MyName=''
while True:
    print("이름을 입력하세요.")
    MyName = input()
    if MyName == 'hongkildong':
        break
print("확인되었습니다.")

# 문제 10 

MyName=''
while True:
    print("이름을 입력하세요.")
    MyName = input()
    if MyName != 'hongkildong':
        continue
    else:
        print("패스워드를 입력하세요.")
        MyPass=input()
        if MyPass=="hahaha":
            break
print("확인되었습니다.")

# 문제 11 - for 문

na = int(input("출력하고자 하는 구구단을 입력하세요."))
for sb in range(1, 10, 1):
    print(na, "*", sb, "=", na * sb )

# 문제 11 - while 문

na = int(input("출력하고자 하는 구구단을 입력하세요"))
nb = 1
while nb < 10:
    print(na, "*", nb, "=", na * nb )
    nb = nb + 1

# 문제 12 - 1

for i in range(1, 6):
  for j in range(1, i+1):
    print(j, end=' ')
  print()

# 문제 12 - 2

for i in range(5):
  for j in range(i + 1):
    print(chr(65 + j), end=' ')
print()

# 문제 12 - 3

for i in range(5):
  for j in range(5):
      print('*', end='')
  print()