# -*- coding: utf-8 -*-
"""파이썬 워크북 6장 문제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nGxYLeGWsVQ0UcsmcyAZZD4R6ScxLw2e

파이썬 워크북 6장 문제
"""

# 문제 1

def fadd(pa, pb):
    pc = pa + pb
    return pc
def fsub(pa, pb):
    pc = pa - pb
    return pc
def fmul(pa, pb):
    pc = pa * pb
    return pc
def fdiv(pa, pb):
    pc = pa / pb
    return pc

na = 100
nb = 3
nc = fadd(na, nb)
print(na, "+", nb, "결괏값은", nc,"이다.")
nd = fsub(na, nb)
print(na, "-", nb, "결괏값은", nd,"이다.")
ne = fmul(na, nb)
print(na, "*", nb, "결괏값은", ne,"이다.")
nf = fdiv(na, nb)
print(na, "/", nb, "결괏값은", nf,"이다.")

# 문제 2

def fadd(pa, pb):
    pc = pa + pb
    return pc
def fsub(pa, pb):
    pc = pa - pb
    return pc
def fmul(pa, pb):
    pc = pa * pb
    return pc
def fdiv(pa, pb):
    pc = pa / pb
    return pc

na = float(input("연산을 위한 첫 번째 값을 입력하세요."))
nb = float(input("연산을 위한 두 번째 값을 입력하세요."))
nc = fadd(na, nb)
print(na, "+", nb, "결괏값은", nc,"이다")
nd = fsub(na, nb)
print(na, "-", nb, "결괏값은", nd,"이다.")
ne = fmul(na, nb)
print(na, "*", nb, "결괏값은", ne,"이다.")
nf = fdiv(na, nb)
print(na, "/", nb, "결괏값은", nf,"이다.")

# 문제 3

sta = "python example"
def string_length(stb):
    count = 0
    for char in stb:
        count = count + 1
    return count

lena = string_length(sta)
print(lena)

# 문제 4

def fdiv(pa, pb):
    if pb == 0:
        return "0으로 나눌 수 없음"
    else:
        return pa/pb
na = 10
nb = 0
nc = fdiv(na, nb)
print(nc)

# 문제 5 - for 문

na=int(input("배수의 합을 구하고자 하는 정수를 입력하세요."))
total = 0
for sb in range(1, 101, 1):
    if sb % na == 0:
        total = total + sb
print("100까지", na,"의 배수의 총합은", total,"이다.")

# 문제 5 - while 문

na=int(input("배수의 합을 구하고자 하는 정수를 입력하세요."))
total = 0
sb=1
while sb < 101:
    if sb % na == 0:
        total = total + sb
    sb = sb + 1
print("100까지", na,"의 배수의 총합은", total,"이다.")

# 문제 5 - for 문을 함수 이름 cunca 함수로 정의하고 호출

def funca(nb):
    total = 0
    for sb in range(1, 101, 1):
        if sb % na == 0:
            total = total + sb
    return total

na=int(input("배수의 합을 구하고자 하는 정수를 입력하세요."))
nc=funca(na)
print("100까지", na,"의 배수의 총합은", nc,"이다.")