# -*- coding: utf-8 -*-
"""파이썬 워크북 5장 문제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ST8soO_05-8NDP_3vPy3vHhZCGhbZaAE

파이썬 워크북 5장 문제
"""

# 문제 1

print("월요일부터 일요일 중 영어로 번역하고 싶은 요일을 입력하세요.")
yoil=input()
if yoil == "월요일":
    print("monday")
elif yoil == "화요일":
    print("tuesday")
elif yoil == "수요일":
    print("wednesday")
elif yoil == "목요일":
    print("thursday")
elif yoil == "금요일":
    print("friday")
elif yoil == "토요일":
    print("saturday")
else:
    print("sunday")

# 문제 2

dicta={"월요일":"monday", "화요일":"tuesday", "수요일":"wednesday", "목요일":"thursday", "금요일":"friday", "토요일":"saturday", "일요일":"sunday"}
print("월요일부터 일요일 중 영어로 번역하고 싶은 요일을 입력하세요.")
yoil=input()
print(dicta[yoil])

# 문제 3

dicta={"월요일":"monday", "화요일":"tuesday", "수요일":"wednesday", "목요일":"thursday", "금요일":"friday", "토요일":"saturday", "일요일":"sunday"}
print("월요일부터 일요일 중 영어로 번역하고 싶은 요일을 입력하세요.")
yoil=input()
if yoil in dicta:
    print(dicta[yoil])
else:
    print("요일을 잘못 입력했어요.")