# -*- coding: utf-8 -*-
"""파이썬 워크북 8장 문제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S1ZJ5cHzTH2d50mw-kYMrr7FXFJMDoge

파이썬 워크북 8장 문제
"""

# 문제 1

ca=[10,17,13,11]
max=ca[0]
if max < ca[1]:
    max = ca[1]
if max < ca[2]:
    max = ca[2]
if max < ca[3]:
    max = ca[3]
print(max)

# 문제 2

ca=[10,17,13,11]
max=ca[0]
for sb in range(1, 4, 1):
    if max < ca[sb]:
        max = ca[sb]
print(max)

# 문제 3 

ca=[10,17,13,11]
max=ca[0]
for sb in ca:
    if max < sb:
        max = sb
print(max)

# 문제 4

# 선택 정렬
ca=[21,10,11,15,13]

for sa in range(0, 4, 1):
    mina=ca[sa]
    minix=sa
    for sb in range(sa+1, 5, 1):
        if mina > ca[sb]:
            mina = ca[sb]
            minix = sb
    temp = ca[sa]
    ca[sa] = ca[minix]
    ca[minix] = temp
    print(ca)

# 문제 5

# 선택 정렬
def fselsort(ca):
    for sa in range(0, 4, 1):
        mina=ca[sa]
        minix=sa
        for sb in range(sa+1, 5, 1):
          if mina > ca[sb]:
              mina = ca[sb]
              minix = sb
        temp = ca[sa]
        ca[sa] = ca[minix]
        ca[minix] = temp

        
ca=[21,10,11,15,13]
fselsort(ca)
print(ca)

def fnin(fu):
    min=fum[0]
    for i in range(1,5,1):
        if min > fu[i]:
              min = fu[i]
    return min