# -*- coding: utf-8 -*-
"""파이썬 워크북 2장 문제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VBVzt3ll0OGsqQ9l1XAVPm4eiaycCYE_

파이썬 워크북 2장 문제
"""

# 문제 1

age = 14
print("당신의 나이는"+age+"살입니다")

# 문제 1 - 수정 코드

age = 14
print("당신의 나이는 " + str(age) + "살입니다.")

# 문제 2

principal = 2550000 # 원금 # ----------> ①
interest_rate = 0.041 # 이자율 (4.1%) # --> ②
periods = 12 # 기간 (12개월)

# 총 이자 계산
total_interest = principal * interest_rate * periods

# 만기 후 총 금액 계산
total_amount = principal + total_interest

# 출력
print("만기 후 총 금액은", format(total_amount, ",.0f"), "원 입니다.")

# 문제 3

myname = "홍길동"
myhackbun = "1234567"
myhakkwa = "국문학과"
myhakjum = "4.2"

print("내 이름은", myname, "학번은", myhackbun, "학과는", myhakkwa, "이전 학점은", myhakjum,"이다")